"""
Automatic chunk validator - Complete chunking system verification

Analyzes all generated chunks to ensure:
1. Adequate size for LLM
2. Correct divisions respecting vulnerability structure
3. Data integrity (no truncation)
4. Optimization for better extraction quality
"""

import os
import sys
project_root = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
if project_root not in sys.path:
    sys.path.insert(0, project_root)

from src.utils.pdf_loader import load_pdf_with_pypdf2
from src.utils.chunking import get_token_based_chunks, split_text_to_subchunks, detect_scanner_pattern
from src.model_management import load_profile, load_llm
import tiktoken
import re


class ChunkValidator:
    def __init__(self, pdf_path: str, profile_name: str = 'default', llm_name: str = 'gpt4'):
        self.pdf_path = pdf_path
        self.profile_config = load_profile(profile_name)
        self.llm_config = load_llm(llm_name)
        
        # SIMPLIFIED CONFIGURATION
        if 'max_chunk_size' in self.llm_config:
            self.max_tokens = self.llm_config['max_chunk_size'] + self.llm_config.get('reserve_for_response', 1500)
        else:
            self.max_tokens = self.llm_config.get('max_tokens', 4096)
        
        try:
            self.tokenizer = tiktoken.encoding_for_model("gpt-3.5-turbo")
        except:
            self.tokenizer = tiktoken.get_encoding("cl100k_base")
            
        print(f"Validator: {os.path.basename(pdf_path)} | {profile_name} | {llm_name}")
        print(f"Max tokens: {self.max_tokens}")
        print(f"{'='*70}")
    
    def load_and_analyze_document(self):
        """Load document and analyze complete text"""
        print("[LOADING] Loading document...")
        
        # Check if it's a .txt file or PDF
        if self.pdf_path.endswith('.txt'):
            print("[FILE] Detected text file (.txt)")
            try:
                with open(self.pdf_path, 'r', encoding='utf-8') as f:
                    text = f.read()
            except Exception as e:
                print(f"[ERROR] Error reading text file: {e}")
                return None
        else:
            print("[FILE] Detected PDF file")
            text = load_pdf_with_pypdf2(self.pdf_path)
        
        if not text:
            print("[ERROR] Unable to load document")
            return None
            
        print(f"[SUCCESS] Document loaded: {len(text):,} characters")
        
        pattern_info = detect_scanner_pattern(text)
        print(f"Detected scanner: {pattern_info['scanner_type'].upper()}")
        print(f"Markers found: {pattern_info['markers_found']}")
        print(f"Uses pairs BASE+INSTANCES: {pattern_info['has_pairs']}")
        
        return text, pattern_info
    
    def analyze_chunks(self, text: str, pattern_info: dict):
        """Analyze chunks generated by current system"""
        print(f"\n{'='*70}")
        print("Chunk Analysis:")
        print(f"{'='*70}")
        
        # Generate chunks using current system
        chunks = get_token_based_chunks(text, self.max_tokens, 
                                       llm_config=self.llm_config,
                                       profile_config=self.profile_config)
        
        print(f"Chunks: {len(chunks)}")
        print(f"Analysis:\n")
        
        issues_found = []
        max_content_tokens = self.max_tokens - 1500 
        
        for i, chunk in enumerate(chunks, 1):
            token_count = len(self.tokenizer.encode(chunk.page_content))
            markers = self._count_vulnerability_markers(chunk.page_content, pattern_info)
            begins_cleanly = self._check_clean_beginning(chunk.page_content, pattern_info)
            ends_cleanly = self._check_clean_ending(chunk.page_content, pattern_info)
            
            size_ok = token_count <= max_content_tokens
            struct_ok = begins_cleanly and ends_cleanly
            
            print(f"🧩 {i:2d}: {token_count:4d}t, {markers:2d}m, {'✅' if size_ok else '❌'}, {'✅' if struct_ok else '❌'}")
            
            if not size_ok:
                issues_found.append(f"Chunk {i}: {token_count} tokens > {max_content_tokens}")
            if not begins_cleanly:
                issues_found.append(f"Chunk {i}: Truncated start")
            if not ends_cleanly:
                issues_found.append(f"Chunk {i}: Final truncado")
            if not ends_cleanly:
                issues_found.append(f"Chunk {i}: Final truncado")
        
        print(f"\n📈 Resumo: {len(issues_found)} problemas encontrados")
        return issues_found
    
    def _count_vulnerability_markers(self, text: str, pattern_info: dict) -> int:
        """Conta marcadores de vulnerabilidade no chunk"""
        if not pattern_info['marker_pattern']:
            return 0
        return len(re.findall(pattern_info['marker_pattern'], text, re.MULTILINE))
    
    def _check_clean_beginning(self, text: str, pattern_info: dict) -> bool:
        """Check if chunk starts at appropriate point"""
        if not pattern_info['marker_pattern']:
            return True  # If no pattern, assume OK
        
        lines = text.strip().split('\n')
        if not lines:
            return False
        
        for i, line in enumerate(lines[:10]): 
            if re.search(pattern_info['marker_pattern'], line):
                return True
            
        if pattern_info['scanner_type'] == 'tenable_was':
            search_text = '\n'.join(lines[:15])
            if re.search(pattern_info['marker_pattern'], search_text, re.MULTILINE):
                return True
                
        return False
    
    def _check_clean_ending(self, text: str, pattern_info: dict) -> bool:
        if not pattern_info['marker_pattern']:
            return True
            
        lines = text.strip().split('\n')
        if len(lines) < 3:
            return False
            
        last_lines = '\n'.join(lines[-10:])  
        
        markers_in_end = re.finditer(pattern_info['marker_pattern'], last_lines, re.MULTILINE)
        markers_list = list(markers_in_end)
        
        if markers_list:
            last_marker_pos = markers_list[-1].start()
            content_after = last_lines[last_marker_pos:]
            return len(content_after) > 100  
            
        return True
    
    def _analyze_tenable_pairs(self, text: str) -> str:
        base_vulns = re.findall(r'^\s*VULNERABILITY\s+(CRITICAL|HIGH|MEDIUM|LOW)\s+PLUGIN\s+ID\s+\d+', text, re.MULTILINE)
        instances_vulns = re.findall(r'Instances \(\d+\)', text)
        
        if not base_vulns:
            return "Nenhuma vulnerabilidade BASE encontrada"
        if not instances_vulns:
            return f"{len(base_vulns)} BASE, 0 INSTANCES (possible issue)"
            
        return f"{len(base_vulns)} BASE, {len(instances_vulns)} INSTANCES"
    
    def suggest_improvements(self, issues: list, text: str, pattern_info: dict):
        if not issues:
            print("Sistema de chunking funcionando adequadamente")
            return
            
        print(f"\nPROBLEMAS ({len(issues)}):")
        size_issues = sum(1 for i in issues if "tokens >" in i)
        structure_issues = sum(1 for i in issues if "truncado" in i)
        
        if size_issues:
            print(f"   • {size_issues} chunks muito grandes")
        if structure_issues:
            print(f"   • {structure_issues} chunks with problematic structure")
        
        print("Solutions: Adjust scanner settings in src/configs/scanners/")
        
    def test_alternative_chunking(self, text: str, pattern_info: dict):
        print(f"\nTESTE ALTERNATIVO:")
        max_content_tokens = self.max_tokens - 1500
        chars_per_token = len(text) / len(self.tokenizer.encode(text))
        target_chars = int(max_content_tokens * chars_per_token * 0.9)
        
        alternative_chunks = split_text_to_subchunks(text, target_chars, self.profile_config)
        print(f"Alternativo criaria {len(alternative_chunks)} chunks")
    
    def run_complete_analysis(self):
        print("Analyzing chunks...")
        
        result = self.load_and_analyze_document()
        if not result:
            return
        text, pattern_info = result
        
        issues = self.analyze_chunks(text, pattern_info)
        
        self.suggest_improvements(issues, text, pattern_info) 
        self.test_alternative_chunking(text, pattern_info)
        
        status = "OK" if not issues else f"⚠️ {len(issues)} problemas"
        print(f"\nRESULTADO: {status}")


if __name__ == "__main__":
    import sys
    
    if len(sys.argv) < 2:
        print("Usage: python chunk_validator.py <pdf_path> [profile] [llm]")
        print("Example: python chunk_validator.py report.pdf tenable gpt4")
        sys.exit(1)
    
    pdf_path = sys.argv[1]
    profile = sys.argv[2] if len(sys.argv) > 2 else 'default'
    llm = sys.argv[3] if len(sys.argv) > 3 else 'gpt4'
    
    validator = ChunkValidator(pdf_path, profile, llm)
    validator.run_complete_analysis()